# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  lint:
    docker:
      - image: redislabsmodules/llvm-toolset:latest
    steps:
      - checkout
      - run:
          name: lint
          command: |
            make lint

  sanitize:
    docker:
      - image: redislabsmodules/llvm-toolset:latest
    steps:
      - checkout
      - run:
          name: Install CMAKE
          command: 'apt update -q && apt install -y cmake'
      - run:
          name: Pull Submodules
          command: git submodule update --init --recursive
      - run:
          name: Build & Test with sanitizers
          command: |
            make sanitize

  static-analysis-infer:
    docker:
      - image: redisbench/infer-linux64:1.0.0
    steps:
      - checkout
      - run:
          name: Submodule checkout
          command: git submodule update --init --recursive
      - run:
          name: run fbinfer
          command: |
            CC=clang CXX=clang++ INFER=infer make static-analysis
  build:
    docker:
      - image: "debian:bullseye"
    steps:
      - run:
          name: Installing SUDO
          command: 'apt update && apt install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt update && apt install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt install -y cmake'
      - run:
          name: Installing LCOV
          command: 'apt install -y lcov'
      - run:
          name: Installing CURL
          command: 'apt install -y curl'
      - run:
          name: Installing GIT
          command: 'apt install -y git'
      - checkout
      - run:
          name: Pull Submodules
          command: git submodule update --init --recursive
      - run:
          name: Build & Test
          command: |
            make clean
            make coverage
            cd build && bash <(curl -s https://codecov.io/bash) -f coverage.info -X gcov -x gcov-7 || echo "Codecov did not collect coverage reports"
      - run:
          name: Install benchmark dependencies
          command: |
            apt update
            apt install python3-pip -y
            pip3 install redisbench-admin
      - run:
          name: Benchmark
          command: |
            make bench
            redisbench-admin export \
              --results-format google.benchmark \
              --github_repo $CIRCLE_PROJECT_REPONAME \
              --github_org $CIRCLE_PROJECT_USERNAME \
              --github_branch $CIRCLE_BRANCH \
              --benchmark-result-file results.json



workflows:
  commit:
    jobs:
      - lint
      - build:
          context: common
      - sanitize
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: common
